"""Builder for the frozen text set `dialtone_v1.jsonl`."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

__all__ = ["CATEGORIES", "build", "write"]

DIGITS = [
    "Your confirmation code is 4 7 B 2 9 K.",
    "The reference number is 8 8 3 0 1 5 6.",
    "Please enter your four digit PIN, 6 2 9 4.",
    "Your order number is A B 1 9 2 7 3 4.",
    "The card ending in 4 4 8 1 was declined.",
    "Your account number is 0 0 7 3 2 9 5 8 6 1.",
    "The tracking number is 1 Z 9 9 A A 1 0 3 4 2 5.",
    "Please call back on 6 1 3 5 5 5 0 1 9 8.",
    "Your extension is 4 0 7.",
    "The policy number is P L 8 8 2 3 1 9.",
    "Enter the six digit code 3 1 4 1 5 9.",
    "The invoice number is I N V 2 0 2 6 0 8 1 4.",
    "Your ticket is number 7 7 2 in the queue.",
    "The security code is 9 0 5 5.",
    "Please verify the last four digits, 3 8 2 6.",
    "Your booking reference is X Q 4 4 9 2.",
    "The meter reading is 0 4 8 2 9 1.",
    "Dial 1 8 0 0 5 5 5 0 1 4 7 for support.",
    "The serial number is S N 4 4 1 9 0 2 8 7 3.",
    "Your case number is C 2 0 2 6 0 0 8 4 1 5.",
    "The postal code is K 7 A 3 M 9.",
    "Please enter your member number, 5 5 0 9 8 8 3.",
    "The batch code reads L T 0 8 1 4 2 6.",
    "Your temporary password is 7 F 3 Q 9 M 2 X.",
    "The unit number is 1 4 0 2 B.",
    "Confirm the last four digits of the amount, 2 4 7 0.",
    "The gate number is C 1 7.",
    "Your loyalty number ends in 9 9 0 2.",
    "The part number is 3 M 8 8 4 0 1 2.",
    "Please quote reference 6 6 2 slash 0 9.",
    "The transaction ID is T X N 4 8 2 9 3 0 1 7 5.",
    "Your PIN has been reset to 1 1 2 4.",
    "The flight number is A C 8 5 4.",
    "Room number 2 0 8 is ready for you.",
    "The verification code expires in 1 0 minutes, it is 4 4 9 2 0 3.",
    "Your file number is F 9 9 0 2 8.",
    "The route number is 4 0 1 west.",
    "Enter your date of birth as 0 3 1 1 1 9 8 8.",
    "The claim number is C L M 7 3 0 2 9 4.",
    "Your queue position is 1 4 of 2 2.",
    "The device ID is D V 8 8 0 0 3 2 1.",
    "Please confirm the digits 5 5 5 5 5 5 5.",
    "The lot number is 2 0 2 6 0 3 A.",
    "Your access code is 8 8 8 8 dash 1 2 3 4.",
    "The bin location is B 4 aisle 1 2.",
    "Call the direct line, 4 1 6 5 5 5 7 7 3 1.",
    "The permit number is P 4 4 0 9 8 2.",
    "Your reference is 9 9 9 dash A A dash 0 1.",
    "The badge number is 4 4 8 2.",
    "Please enter the last six digits, 2 0 9 8 4 1.",
    "The contract number is 0 0 0 8 8 2 4 1 9 6.",
    "Your shipment is number 3 of 7.",
    "The pump number is 0 6.",
    "Enter your postal code, M 5 V 2 T 6.",
    "The IMEI is 3 5 4 8 2 0 1 1 9 4 7 3 0 2 6.",
    "Your appointment number is 1 1 4 8.",
    "The SKU is 7 7 0 4 2 1 8 8 3.",
    "Please read back the code, Q 4 R 7 T 2.",
    "The account PIN is 0 0 4 9.",
    "Your survey code is 6 1 9 4 4 2 8.",
]

PROPER_NOUNS = [
    "I have you booked with Doctor Aisling Fitzgerald.",
    "Your technician today is Rajesh Venkataraman.",
    "Please ask for Siobhan at the front desk.",
    "The account is under the name Nguyen Thi Hoa.",
    "You were speaking with Bartholomew Kowalczyk earlier.",
    "The referral came from Doctor Chukwuemeka Adeyemi.",
    "I will transfer you to Yekaterina Volkova.",
    "The file is assigned to Guadalupe Hernandez.",
    "Your case worker is Thaddeus Okonkwo.",
    "Please confirm the surname, it is spelled Featherstonehaugh.",
    "The invoice is addressed to Bergstrom and Lindqvist Limited.",
    "You have an appointment with Priya Balasubramanian.",
    "The claim was filed by Wojciech Szymanski.",
    "I show the policy under Mairead O'Sullivan.",
    "The delivery is for Kwame Boateng.",
    "Your consultant is Anneliese Schumacher.",
    "The order was placed by Hyun Woo Park.",
    "Please hold for Giovanni Castellucci.",
    "The account manager is Fatima Al Mansouri.",
    "Your prescription was written by Doctor Ingrid Halvorsen.",
    "The property is listed by Cavanagh and Doyle Realty.",
    "I have a note from Dmitri Sokolov.",
    "The reservation is under Xiaoming Zhang.",
    "Your representative is Oluwaseun Adebayo.",
    "The contractor is Zbigniew Wojciechowski.",
    "Please contact Meredith Fairweather about the invoice.",
    "The estimate came from Thibault Lefebvre.",
    "Your dentist is Doctor Saoirse Gallagher.",
    "The shipment is going to Reykjavik.",
    "I can connect you to the Saskatoon branch.",
    "The office is in Mississauga.",
    "We have locations in Kitchener and Waterloo.",
    "The warehouse is in Tsawwassen.",
    "Your parcel is in transit through Antananarivo.",
    "The regional office covers Charlottetown.",
    "Please visit our Etobicoke location.",
    "The clinic is on the Chilliwack side.",
    "Deliveries to Yellowknife take longer.",
    "Our head office is in Sault Sainte Marie.",
    "The depot is near Kamloops.",
    "You can pick it up in Oshawa.",
    "The service area includes Nanaimo and Courtenay.",
    "Your account was opened in Gatineau.",
    "The branch in Moncton closes early.",
    "We ship from Brampton daily.",
    "The audit was done by Pricewaterhouse and Associates.",
    "Your plan is with Manulife Financial.",
    "The carrier is Purolator.",
    "The supplier is Thyssenkrupp Elevator.",
    "Please reference the Wolseley account.",
]

ADDRESSES = [
    "The address is 1427 Elm Street, apartment 3B.",
    "Deliver to 88 Wellington Avenue West.",
    "Our office is at 205 Bay Street, suite 1400.",
    "The site is 6631 Highway 401 East.",
    "Please go to 9 Rue Saint Catherine Ouest.",
    "The unit is 12-440 Sheppard Avenue East.",
    "It is 777 Boulevard Rene Levesque.",
    "The pickup point is 3310 Concession Road 5.",
    "We are at 15 Front Street North, unit C.",
    "The clinic is at 4022 Lakeshore Boulevard West.",
    "Ship to 981 Industrial Parkway South.",
    "The warehouse is 1100 Airport Road, bay 7.",
    "The house number is 64 on Maple Crescent.",
    "Go to 2345 Queen Street East, rear entrance.",
    "The address on file is 508 Grosvenor Terrace.",
    "It is 1902 Rural Route 3.",
    "The building is 300 University Avenue, floor 12.",
    "Please deliver to 44 Sixth Line, Post Office Box 220.",
    "The property is at 1788 Old Mill Road.",
    "Our depot is 600 Commissioners Street.",
    "The suite is 805 at 121 King Street West.",
    "Try 29 Beechwood Drive, the side door.",
    "The mailing address is Post Office Box 4492, station A.",
    "It is 333 Rue Notre Dame Est.",
    "The shop is at 1015 Danforth Avenue.",
    "We are located at 7200 Trans Canada Highway.",
    "The lot is 14 on Concession 8, township of Zorra.",
    "Deliver to 555 Rene Levesque Boulevard West, level 2.",
    "The address is 21 Church Street, Sarnia Ontario.",
    "The unit number is 410 at 90 Absolute Avenue.",
    "Please note 1337 Saint Clair Avenue West.",
    "The location is 8440 Ninth Line, Halton Hills.",
    "It is 66 Wellesley Street East, buzzer 304.",
    "The receiving dock is at 4500 Dixie Road.",
    "Head to 111 Peter Street, suite 901.",
    "The farm is at 3380 Sideroad 17.",
    "Our branch is 2450 Ottawa Street South.",
    "The address is 909 Rue Sherbrooke Ouest.",
    "Go to 164 Cumberland Street, lower level.",
    "The site address is 55 Confederation Drive, gate 2.",
]

DATETIME_MONEY = [
    "Your appointment is March 3rd at 2:15 pm.",
    "The total comes to $1,247.50.",
    "We are open from 8:30 am until 5:45 pm.",
    "The balance owing is $89.99.",
    "Your payment of $345.00 was received on July 22nd.",
    "The appointment is Tuesday the 14th at 11:00 am.",
    "That will be $6.75 altogether.",
    "The deadline is the 31st of January, 2027.",
    "Your refund of $219.40 is processing.",
    "We will call between 1:00 pm and 3:00 pm on Thursday.",
    "The monthly fee is $49.95.",
    "It was posted on August 14th at 9:07 am.",
    "The quote is valid until September 30th.",
    "Your last payment was $1,100.00 exactly.",
    "The office closes at 4:30 pm on Fridays.",
    "That comes to $33.33 after tax.",
    "Your policy renews on the 1st of December.",
    "The charge was $780.25 on the statement.",
    "We can see you at 7:45 am tomorrow.",
    "The invoice is dated February 29th, 2028.",
    "Your credit is $50.05 on the account.",
    "The appointment ran from 10:15 am to 11:50 am.",
    "The annual premium is $2,468.00 this year.",
    "Delivery is expected on the 3rd or 4th of next month.",
    "You were billed $15.00 for the visit.",
    "The meeting is at 12:00 pm on Wednesday.",
    "That is a savings of $305.80 per year.",
    "The store opens at 9:00 am on statutory holidays.",
    "Your term ends October 17th, 2029.",
    "The deposit is $500.00 and refundable.",
    "It happened on the 22nd of June at 6:03 pm.",
    "The hourly rate is $85.50 plus tax.",
    "We close for lunch from 12:30 pm to 1:15 pm.",
    "The outstanding amount is $924.17 today.",
    "Your next visit is Monday the 8th at 3:20 pm.",
    "The fee increased to $12.45 in April.",
    "Payment is due within 30 days of April 5th.",
    "The total including tax is $113.01 exactly.",
    "The window is 8:00 am to 12:00 pm on the 19th.",
    "You saved $44.44 this quarter.",
]

CONVERSATIONAL = [
    "Thanks for calling. How can I help you today?",
    "Let me pull up your account. One moment please.",
    "I can help you with that. Can I get your name first?",
    "Just so I understand, you want to reschedule rather than cancel?",
    "I am not able to see that from here. Let me check with the team.",
    "Sorry, I did not catch that. Could you say it again?",
    "That is all confirmed. Is there anything else I can do?",
    "I will put you on a brief hold while I look into it.",
    "Thanks for waiting. I have the answer for you now.",
    "It looks like the payment went through this morning.",
    "Would you prefer a morning slot or an afternoon slot?",
    "I want to make sure I have this right before I proceed.",
    "Unfortunately that option is not available on your plan.",
    "Let me transfer you to someone who can help with billing.",
    "Can you confirm the first line of your address for me?",
    "I have updated your file. You should get an email shortly.",
    "The wait time is about four minutes right now.",
    "I understand this is frustrating. Let me see what I can do.",
    "Are you calling about the appointment or the invoice?",
    "That charge appears to be a duplicate. I will refund it.",
    "Your request has been submitted. The reference is in your email.",
    "Do you want me to send that by text or by email?",
    "I am seeing two accounts under that name. Which one is yours?",
    "Give me one second while the system loads.",
    "I can book you in, but the earliest is next Thursday.",
    "Just to confirm, you would like to cancel the whole order?",
    "I have made a note on the account for the next agent.",
    "That department opens at nine in the morning.",
    "Would you like me to stay on the line while you check?",
    "I am afraid I cannot process a refund over the phone.",
    "Your call may be recorded for quality purposes.",
    "Can you tell me a bit more about what happened?",
    "It sounds like the device is not connecting to the network.",
    "Let us try one more thing before I escalate this.",
    "I have sent a technician request for tomorrow morning.",
    "You should see the credit within three business days.",
    "Sorry about the wait. Thanks for your patience.",
    "I will read that back to you to make sure it is correct.",
    "Is this the best number to reach you on?",
    "The account is currently in good standing.",
    "There is a small balance carried over from last month.",
    "I can waive that fee as a one time courtesy.",
    "Would you like to hear the options again?",
    "Press one for sales, or stay on the line for support.",
    "I did not quite hear you. The line is a bit unclear.",
    "Let me repeat that back so we are on the same page.",
    "Your service should be restored within the hour.",
    "I have flagged this for a supervisor to review.",
    "Can you spell that last name for me please?",
    "We do not have any availability that week, sorry.",
    "I will email you a summary of what we discussed.",
    "Are you able to hold for another minute or two?",
    "That is outside our service area, unfortunately.",
    "I can see the technician arrived at eleven.",
    "Your warranty covers parts but not labour.",
    "Let me confirm the spelling of your street name.",
    "I am going to place you on hold to verify that.",
    "Thanks for confirming. I will process it now.",
    "You will receive a call back within two hours.",
    "The system is running slowly today. Bear with me.",
    "I have cancelled the old booking and made the new one.",
    "Do you need directions to the office?",
    "Is there a better time for us to call you back?",
    "I can only discuss the account with the primary holder.",
    "Your identity has been verified. Thank you.",
    "That model has been discontinued, but there is a replacement.",
    "I will send the form to the address on file.",
    "We are experiencing higher than usual call volume.",
    "Everything is set. You are all booked in.",
    "Have a good rest of your day. Goodbye.",
]

GENERAL = [
    "The weather turned cold much earlier than expected this year.",
    "She placed the book on the table and walked to the window.",
    "Most of the equipment was replaced during the last upgrade.",
    "The report suggests a modest improvement over the previous quarter.",
    "He decided to take the longer route through the valley.",
    "The building has stood on that corner for over a century.",
    "Several factors contributed to the delay in production.",
    "They agreed to meet again once the results were available.",
    "The instructions were clear but the diagram was confusing.",
    "A small crowd had gathered near the entrance by then.",
    "The machine stopped working shortly after the power returned.",
    "Her explanation made sense once the context was clear.",
    "The committee reviewed all the submissions before deciding.",
    "There is a noticeable difference between the two samples.",
    "The road was closed for repairs until late in the evening.",
    "We should consider the alternative before committing resources.",
    "The train arrived just as the announcement was finishing.",
    "It took three attempts before the connection was stable.",
    "The garden looks completely different in the autumn light.",
    "Neither option seemed particularly attractive at the time.",
    "The measurements were repeated to confirm the original finding.",
    "He remembered the conversation quite differently than she did.",
    "The software update introduced several unexpected problems.",
    "Water damage was found behind the wall during the inspection.",
    "The old bridge is scheduled for demolition next spring.",
    "Attendance was lower than the organisers had hoped.",
    "The recipe calls for ingredients that are hard to find locally.",
    "She has worked in the same department for eleven years.",
    "The path continues past the fence and into the woods.",
    "Nothing in the file explained the discrepancy.",
    "The lecture covered material that was new to most of us.",
    "They rebuilt the engine using parts from two other vehicles.",
    "The colour appears lighter under artificial lighting.",
    "A second opinion confirmed what the first had suggested.",
    "The lease expires before the renovation will be finished.",
    "Everyone agreed the presentation had gone rather well.",
    "The noise from the construction site starts early each morning.",
    "His handwriting was difficult to read on the carbon copy.",
    "The results were consistent across all three trials.",
    "Snow had covered the tracks by the time they returned.",
]

CATEGORIES: dict[str, list[str]] = {
    "digits": DIGITS,
    "proper_nouns": PROPER_NOUNS,
    "addresses": ADDRESSES,
    "datetime_money": DATETIME_MONEY,
    "conversational": CONVERSATIONAL,
    "general": GENERAL,
}

EXPECTED_COUNTS = {
    "digits": 60,
    "proper_nouns": 50,
    "addresses": 40,
    "datetime_money": 40,
    "conversational": 70,
    "general": 40,
}


def build() -> list[dict]:
    """Assemble the records in a fixed order, so the file hash is stable."""
    for name, expected in EXPECTED_COUNTS.items():
        actual = len(CATEGORIES[name])
        if actual != expected:
            raise ValueError(
                f"category {name!r} has {actual} entries, expected {expected}"
            )

    seen: set[str] = set()
    records: list[dict] = []
    index = 0
    for category in EXPECTED_COUNTS:
        for text in CATEGORIES[category]:
            if text in seen:
                raise ValueError(f"duplicate text: {text!r}")
            seen.add(text)
            index += 1
            records.append(
                {
                    "utterance_id": f"dt-{index:04d}",
                    "text": text,
                    "category": category,
                    "n_words": len(text.split()),
                }
            )
    return records


def write(path: Path) -> str:
    """Write the JSONL and return its sha256."""
    lines = [json.dumps(r, ensure_ascii=False, sort_keys=True) for r in build()]
    payload = "\n".join(lines) + "\n"
    path.write_text(payload, encoding="utf-8")
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


if __name__ == "__main__":
    target = Path(__file__).parent / "dialtone_v1.jsonl"
    digest = write(target)
    records = build()
    print(f"wrote {len(records)} utterances to {target}")
    print(f"total words: {sum(r['n_words'] for r in records)}")
    print(f"sha256: {digest}")
